[http::debprog]
# url = https://10.69.0.220:8088/services/collector/event
# url = https://10.69.0.220:8089/services/receivers/simple
url = https://10.69.0.220:8089/services/receivers/stream
# url = https://10.69.0.100:8089/services/listener/collector
token = 3812323b-211b-430a-a660-7551c5170f4a